# Generated by Django 4.1 on 2023-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="last_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Last update"),
        ),
    ]
