# Generated by Django 4.1 on 2023-06-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0003_posts_last_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.IntegerField(default=0, verbose_name="Followers"),
        ),
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.IntegerField(default=0, verbose_name="Following"),
        ),
    ]
