# Generated by Django 4.1 on 2023-01-14 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                default="No Category",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type",
                to="auctions.categories",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lover",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watchlist",
                    models.ManyToManyField(
                        blank=True, related_name="favorited", to="auctions.listing"
                    ),
                ),
            ],
        ),
    ]
