# Generated by Django 4.1 on 2023-01-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_listing_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="bid",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="offers", to="auctions.bid"
            ),
        ),
    ]
