# Generated by Django 4.1 on 2023-01-10 22:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="creation",
            field=models.TimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="image_url",
            field=models.URLField(max_length=300),
        ),
    ]
