# Generated by Django 4.1 on 2023-01-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_listing_creation_alter_listing_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="creation",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
