# Generated by Django 4.1 on 2023-01-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_listing_bid"),
    ]

    operations = [
        migrations.RemoveField(model_name="listing", name="bid",),
        migrations.AddField(
            model_name="listing",
            name="bid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="offers",
                to="auctions.bid",
            ),
        ),
    ]
