# Generated by Django 4.1 on 2023-01-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_comments_listing_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="bids_count",
            field=models.IntegerField(default=1),
        ),
    ]
