# Generated by Django 4.1 on 2023-01-21 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_listing_bids_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lover",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
