# Generated by Django 4.1 on 2023-01-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_watchlist_user"),
    ]

    operations = [
        migrations.DeleteModel(name="Watchlist",),
    ]
