# Generated by Django 4.1 on 2023-01-21 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_delete_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="watchlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
